### ISSUE TITLE
Can you provide some code to help me complete it?

### ISSUE THREAD

**Issue by PYL4869** [ETH-PBL/TinyissimoYOLO#1]
Hi
I learned about TinyissimoYOLO through [this paper](https://arxiv.org/abs/2306.00001), and I am trying to deploy the TinyissimoYOLO model on the MAX78000FTHR, but I found that there seems to be no relevant content here. Can you provide some necessary codes and instructions? Such as the model and dataloader required for training, and the networks (.yaml) required to generate C code,and the instructions used for training and generating C code.

This is my email: w2749332289@gmail.com.
Thanks.

**Comment by mojulian** [comment]
Hi,
Thanks for your interest in our work. The code requested for the initial TinyissimoYOLO paper is not yet open-sourced. However, we are currently developing all networks which are used for deployment on microcontrollers, within the framework provided by this repository. All relevant information you're looking for can be found in the paper you mentioned or in the recently published: [TinyissimoYOLO ACCESS journal](https://ieeexplore.ieee.org/document/10538092)
